// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZombieControl.Data;

namespace ZombieController.Migrations
{
    [DbContext(typeof(ZombieContext))]
    partial class ZombieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZombieControl.Model.Command", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommandText");

                    b.Property<DateTime>("RunAfter");

                    b.Property<DateTime>("RunBefore");

                    b.Property<Guid?>("ZombieId");

                    b.HasKey("CommandId");

                    b.HasIndex("ZombieId");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("ZombieControl.Model.Zombie", b =>
                {
                    b.Property<Guid>("ZombieId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastReportedIPAddress");

                    b.HasKey("ZombieId");

                    b.ToTable("Zombies");
                });

            modelBuilder.Entity("ZombieControl.Model.Command", b =>
                {
                    b.HasOne("ZombieControl.Model.Zombie", "Zombie")
                        .WithMany()
                        .HasForeignKey("ZombieId");
                });
#pragma warning restore 612, 618
        }
    }
}
